



stages:
  - build
  - push



build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script:
  #   - apt update && apt -y install make autoconf
  script:
    - echo "User is "$USER
#    - mkdir obj bin
    - docker run -v `pwd`:`pwd` -w `pwd` sovietlinux make && make formats
    - echo "GOOOD"


# run tests using the binary built before
push:
  stage: push
  script:
     - echo "push to repo"
     - git push ssh://git@github.com/Soviet-Linux/CCCP.git HEAD:main
