name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: apt install libcurl4-openssl-dev
    - name: make all
      run: make all
    - name: make check
      run: make check
    - name: make test
      run: make test
