name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install libcurl-dev
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev
      if: runner.os == 'Linux' || runner.os == 'Ubuntu'

    - name: Install libcurl-dev (macOS)
      run: |
        brew update
        brew install libcurl
      if: runner.os == 'macOS'

    - name: Make all
      run: make all

    - name: Make check
      run: make check

    - name: Make test
      run: make test
