name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install libcurl-dev
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libgit2-dev

    - name: Make all
      run: make all
    - name: Make formats
      run: make formats
    - name: Make install
      run: sudo make install

    - name: Make check
      run: sudo make check
